name: tsa-project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - pytorch::pytorch
  - seaborn
  - scipy
  - ipykernel
  - r-base
  - rpy2
  - r-msgarch
  - gcc_linux-64
  - gxx_linux-64
  - setuptools
  - pmdarima<=1.8.5
  - pip:
      - statsmodels
      - arch
      - yfinance
      - holidays==0.24
      - prophet<=1.1.5
      - cmdstanpy
      - greykite
      - orbit-ml
