name: tsa-project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - pytorch::pytorch
  - seaborn
  - scipy
  - ipykernel
  - r-base
  - rpy2
  - setuptools
  - pmdarima
  - pip:
      - statsmodels
      - arch
      - yfinance
      - prophet
      - cmdstanpy
      - greykite
      - orbit-ml
